services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgresql_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test123
      - POSTGRES_USER=root
      - POSTGRES_DB=fire_backend

  backend:
    build: ./backend/.
    volumes:
      - ./backend/src:/app/src
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend/.
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - "5173:5173"

volumes:
    postgresql_db: