services:
  postgres:
    image: postgis/postgis:17-3.5-alpine
    platform: linux/amd64
    ports:
      - "5432:5432"
    volumes:
      - postgresql_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test123
      - POSTGRES_USER=root
      - POSTGRES_DB=fire_backend

  backend:
    build: ./backend/.
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=test123
      - DB_NAME=fire_backend
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - postgres
      - redis

  mailserver:
    image: axllent/mailpit
    ports:
      - "1025:1025" 
      - "8025:8025"

  frontend:
    build: ./frontend/.
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/public:/app/public
    ports:
      - "5173:5173"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
    postgresql_db:
    redis_data:
