"""create_event_vehicles_association_table

Revision ID: 45cab0cd3ab2
Revises: 679ce7cad963
Create Date: 2025-04-11 09:26:18.108373

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45cab0cd3ab2"
down_revision: Union[str, None] = "679ce7cad963"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_vehicles",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["event.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicletype.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id", "vehicle_id"),
    )
    op.drop_constraint("event_vehicle_id_fkey", "event", type_="foreignkey")
    op.drop_column("event", "vehicle_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event",
        sa.Column("vehicle_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "event_vehicle_id_fkey", "event", "vehicletype", ["vehicle_id"], ["id"]
    )
    op.drop_table("event_vehicles")
    # ### end Alembic commands ###
