"""add deactivated field to user

Revision ID: 644a059d596e
Revises: 7323e32d444a
Create Date: 2025-06-05 20:49:29.273764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "644a059d596e"
down_revision: Union[str, None] = "7323e32d444a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("deactivated", sa.Boolean(), server_default="False", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "deactivated")
    # ### end Alembic commands ###
