"""create invite table

Revision ID: a91f9c0d6424
Revises: cf1bc9f4ba0d
Create Date: 2025-03-18 21:58:22.238117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a91f9c0d6424"
down_revision: Union[str, None] = "cf1bc9f4ba0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invite",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("invite_uuid", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("expire_date", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invite_email"), "invite", ["email"], unique=False)
    op.create_index(op.f("ix_invite_id"), "invite", ["id"], unique=False)
    op.create_index(
        op.f("ix_invite_invite_uuid"), "invite", ["invite_uuid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invite_invite_uuid"), table_name="invite")
    op.drop_index(op.f("ix_invite_id"), table_name="invite")
    op.drop_index(op.f("ix_invite_email"), table_name="invite")
    op.drop_table("invite")
    # ### end Alembic commands ###
