"""add password reset table

Revision ID: b3f1951afce0
Revises: 644a059d596e
Create Date: 2025-07-28 23:51:15.354285

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "b3f1951afce0"
down_revision: Union[str, None] = "644a059d596e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pw_reset",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "reset_type",
            sa.Enum("ADMIN", "SELF", "FORGOT", name="passwordresettype"),
            nullable=False,
        ),
        sa.Column("reset_code", sa.String(), nullable=True),
        sa.Column("reset_token", sa.String(), nullable=True),
        sa.Column("expire_date", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("for_user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["for_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pw_reset_for_user_id"), "pw_reset", ["for_user_id"], unique=False
    )
    op.create_index(op.f("ix_pw_reset_id"), "pw_reset", ["id"], unique=False)
    op.create_index(
        op.f("ix_pw_reset_reset_code"), "pw_reset", ["reset_code"], unique=True
    )
    op.create_index(
        op.f("ix_pw_reset_reset_token"), "pw_reset", ["reset_token"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pw_reset_reset_token"), table_name="pw_reset")
    op.drop_index(op.f("ix_pw_reset_reset_code"), table_name="pw_reset")
    op.drop_index(op.f("ix_pw_reset_id"), table_name="pw_reset")
    op.drop_index(op.f("ix_pw_reset_for_user_id"), table_name="pw_reset")
    op.drop_table("pw_reset")
    op.execute("DROP TYPE passwordresettype;")
    # ### end Alembic commands ###
