"""add_user_email_first_last_name

Revision ID: ca1848da518d
Revises: 45cab0cd3ab2
Create Date: 2025-04-11 12:27:47.757222

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca1848da518d"
down_revision: Union[str, None] = "45cab0cd3ab2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sa.String(), nullable=False))
    op.add_column(
        "user", sa.Column("first_name", sa.String(length=100), nullable=False)
    )
    op.add_column("user", sa.Column("last_name", sa.String(length=100), nullable=False))
    op.drop_index("ix_user_username", table_name="user")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.drop_column("user", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index("ix_user_username", "user", ["username"], unique=True)
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
